plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - readme.md
theme: jekyll-theme-cayman
title: Belajar Form Data
baseurl: "learning-form-data"
url: ""
